### ISSUE TITLE
[Android 14] INSTALL_FAILED_DEPRECATED_SDK_VERSION Error (Alternate Solution Available)

### ISSUE THREAD

**Issue by markusltnr** [KnugiHK/WhatsApp-Key-DB-Extractor#9]
Installing the legacy WhatsApp Version failed in my case. I got the following Error:
```
Installing legacy WhatsApp 2.11.431
Performing Streamed Install
adb: failed to install tmp/LegacyWhatsApp.apk: Failure [INSTALL_FAILED_DEPRECATED_SDK_VERSION: App package must target at least SDK version 23, but found 19]
Install complete! Open Whatsapp, allow the permissions request, if any. Then, press Enter to continue.

```

Is there any solution for that?

**Comment by KnugiHK** [comment]
Try to use this version instead: https://web.archive.org/web/20131203131006/http://www.whatsapp.com/android/current/WhatsApp.apk

**Comment by mr-brune** [comment]
it doesn't work im on android 14

**Comment by Skyaigrette** [comment]
I believe it's the same error: #6  
This error occurred to me, and then I wanted to install the APK directly from my phone. After that, I got error #6  The version is not compatible with your Android version, which is why you have this error.

**Comment by KnugiHK** [comment]
> it doesn't work im on android 14

The INSTALL_FAILED_DEPRECATED_SDK_VERSION error is a known issue with Android 14, which blocks any app with a targetSdkVersion lower than 23 from being installed. You can read more about this behavior change here: https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level.

Sadly, this means the extractor no longer works on Android 14.

For those using Android 14, your best option without rooting is to back up your chats with end-to-end encryption (crypt15) and decrypt the backup file using the generated encryption key.

Alternatively, if your phone isn't up-to-date and remains vulnerable, you could try this solution: https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor/issues/1#issuecomment-2155881641, although I am not sure if it will work properly in an old Android 14.

> I believe it's the same error: https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor/issues/6
This error occurred to me, and then I wanted to install the APK directly from my phone. After that, I got error https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor/issues/6 The version is not compatible with your Android version, which is why you have this error.

@Skyaigrette Are you using Android 14?

**Comment by Skyaigrette** [comment]
@KnugiHK Yes, I am using Android 14, but I managed to solve the issue with a different method to extract the files. I recommend doing this late at night so that you’re won't get any messages.

First, I backed up my WhatsApp data from my phone. Then, I logged into my WhatsApp account on the MeMu Emulator. After restoring my messages, I navigated to "/data/data/com.whatsapp/files/" through the "Storage" section. In that folder, you'll find several files to copy. I only copied the "key" and "wa.db" files since I already had the "msgstore.db.crypt14" file from my phone, which doesn't require root access to retrieve.

Finally, I decrypted "msgstore.db.crypt14" using [wtsexporter](https://github.com/KnugiHK/WhatsApp-Chat-Exporter).

Important note: To access the "data/data..." directory, you need to enable root in the MeMu Emulator settings. It's straightforward—just press a button.
If your phone is already rooted, you don't need to use the MeMu Emulator. I later discovered that you can access that folder by connecting your phone to your laptop, though I'm not entirely sure how to do it.

**Comment by KnugiHK** [comment]
> @KnugiHK Yes, I am using Android 14, but I managed to solve the issue with a different method to extract the files. I recommend doing this late at night so that you’re won't get any messages.
> 
> First, I backed up my WhatsApp data from my phone. Then, I logged into my WhatsApp account on the MeMu Emulator. After restoring my messages, I navigated to "/data/data/com.whatsapp/files/" through the "Storage" section. In that folder, you'll find several files to copy. I only copied the "key" and "wa.db" files since I already had the "msgstore.db.crypt14" file from my phone, which doesn't require root access to retrieve.
> 
> Finally, I decrypted "msgstore.db.crypt14" using [wtsexporter](https://github.com/KnugiHK/WhatsApp-Chat-Exporter).
> 
> Important note: To access the "data/data..." directory, you need to enable root in the MeMu Emulator settings. It's straightforward—just press a button. If your phone is already rooted, you don't need to use the MeMu Emulator. I later discovered that you can access that folder by connecting your phone to your laptop, though I'm not entirely sure how to do it.

Yup. This is also another way to do so.

Since there is nothing we can do to fix the issue, I am closing this issue for now.

**Comment by mirh** [comment]
https://www.cnblogs.com/pieces0310/p/18198819
The issue seems pretty trivial to bypass actually. It's just that no shit you are getting that error when adb hasn't been updated even once in the past decade.

**Comment by NicksonYap** [comment]
> > it doesn't work im on android 14
> 
> The INSTALL_FAILED_DEPRECATED_SDK_VERSION error is a known issue with Android 14, which blocks any app with a targetSdkVersion lower than 23 from being installed. You can read more about this behavior change here: https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level.
> 
> Sadly, this means the extractor no longer works on Android 14.
> 
> For those using Android 14, your best option without rooting is to back up your chats with end-to-end encryption (crypt15) and decrypt the backup file using the generated encryption key.
> 
> Alternatively, if your phone isn't up-to-date and remains vulnerable, you could try this solution: [#1 (comment)](https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor/issues/1#issuecomment-2155881641), although I am not sure if it will work properly in an old Android 14.
> 
> > I believe it's the same error: [#6](https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor/issues/6)
> > This error occurred to me, and then I wanted to install the APK directly from my phone. After that, I got error [#6](https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor/issues/6) The version is not compatible with your Android version, which is why you have this error.
> 
> [@Skyaigrette](https://github.com/Skyaigrette) Are you using Android 14?


Thanks @KnugiHK turning on end to end encrypted backup using 64-digit generated key for Android 14 worked, it changed from `crypt14` to `crypt15` and was able to run command like:

```
wtsexporter -a -k THE_CRYPT15_HEX_KEY_HERE -b "Android-media-com.whatsapp-crypt15\com.whatsapp\WhatsApp\Databases\msgstore.db.crypt15" --media "Android-media-com.whatsapp-crypt15\com.whatsapp\WhatsApp" --experimental-new-theme
```
